### ISSUE TITLE
Multiple recipes for the same target

### ISSUE THREAD

**Issue by ammario** [cdr/nfy#1]
E.g

Given

```yaml
htop:
  install: "pacman -S htop"
deps:
  - pacman
htop:
  install: "apt-get install -y htop"
deps:
  - apt
```

nfy automatically selects the recipe based on the available dependencies.

Courtesy of @nathanpotter
